# Generated by Django 3.2.3 on 2021-05-22 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='person',
            field=models.CharField(default='Name', max_length=200),
            preserve_default=False,
        ),
    ]
